language: python

python:
  - "3.7"

services:
  - postgresql
  - docker

addons:
  chrome: stable
  sonarcloud:
    organization: "sartography"

before_install:
  - psql -c 'create database crc_test;' -U postgres

install:
  - pip install pipenv pytest coverage
  - export PATH=$PATH:$HOME/.local/bin;
  - pipenv install --dev

env:
  global:
    - TESTING=true
    - PB_ENABLED=false
    - SQLALCHEMY_DATABASE_URI="postgresql://postgres:@localhost:5432/crc_test"

script:
  - pipenv run coverage run -m pytest
  - pipenv run coverage xml -i

after_success:
  - sonar-scanner

deploy:
  provider: script
  script: bash deploy.sh sartography/cr-connect-workflow
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(dev|testing|demo|training|staging|master|rrt\/.*)$

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - dan@sartography.com
